export const products = [
    {
        id: 1,
        img: `images/products/pro1.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 2,
        img: `images/products/pro2.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 3,
        img: `images/products/pro3.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 4,
        img: `images/products/pro4.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 5,
        img: `images/products/pro5.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 6,
        img: `images/products/pro6.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 7,
        img: `images/products/pro7.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 8,
        img: `images/products/pro8.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 9,
        img: `images/products/pro9.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
    {
        id: 10,
        img: `images/products/pro10.png`,
        dept: "English Department",
        old_rice: 16.48,
        new_price: 6.48,
    },
]