export const bestseller = [
    {
        id: 1,
        image: `/images/bestseller/bs1.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 2,
        image: `/images/bestseller/bs2.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 3,
        image: `/images/bestseller/bs3.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 4,
        image: `/images/bestseller/bs4.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 5,
        image: `/images/bestseller/bs5.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 6,
        image: `/images/bestseller/bs6.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 7,
        image: `/images/bestseller/bs7.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
    {
        id: 8,
        image: `/images/bestseller/bs8.png`,
        title: 'Graphic Design',
        category: 'English Department',
        price: 16.48,
        discountPercentage: 6.48,
    },
]